### ISSUE TITLE
Cannot find module 'core-js/modules/es.string.replace.js'

### ISSUE THREAD

**Issue by rafgraph** [pastelsky/package-build-stats#37]
When using `package-build-stats v7.2.2` locally I get this error: `Cannot find module 'core-js/modules/es.string.replace.js'`

This is caused be a dependency error in `csso-webpack-plugin` (`core-js` is only listed as a `dependency`). See: https://github.com/zoobestik/csso-webpack-plugin/issues/28

Until `csso-webpack-plugin` publishes a fix, maybe `core-js` could be added as `dependency` to `package-build-stats`?

Full error (from https://github.com/rafgraph/rollpkg/issues/6)
```console
internal/modules/cjs/loader.js:1088
  throw err;
  ^

Error: Cannot find module 'core-js/modules/es.string.replace.js'
Require stack:
- /home/pierre/s/use-nft/node_modules/csso-webpack-plugin/lib/index.js
- /home/pierre/s/use-nft/node_modules/package-build-stats/build/config/makeWebpackConfig.js
- /home/pierre/s/use-nft/node_modules/package-build-stats/build/utils/build.utils.js
- /home/pierre/s/use-nft/node_modules/package-build-stats/build/getPackageStats.js
- /home/pierre/s/use-nft/node_modules/package-build-stats/build/index.js
- /home/pierre/s/use-nft/node_modules/rollpkg/dist/bundlephobiaStats.js
- /home/pierre/s/use-nft/node_modules/rollpkg/dist/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1085:15)
    at Function.Module._load (internal/modules/cjs/loader.js:928:27)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/home/pierre/s/use-nft/node_modules/csso-webpack-plugin/lib/index.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pierre/s/use-nft/node_modules/csso-webpack-plugin/lib/index.js',
    '/home/pierre/s/use-nft/node_modules/package-build-stats/build/config/makeWebpackConfig.js',
    '/home/pierre/s/use-nft/node_modules/package-build-stats/build/utils/build.utils.js',
    '/home/pierre/s/use-nft/node_modules/package-build-stats/build/getPackageStats.js',
    '/home/pierre/s/use-nft/node_modules/package-build-stats/build/index.js',
    '/home/pierre/s/use-nft/node_modules/rollpkg/dist/bundlephobiaStats.js',
    '/home/pierre/s/use-nft/node_modules/rollpkg/dist/cli.js'
  ]
}
```

**Comment by rafgraph** [comment]
Note that I didn't encounter this issue until I regenerated my project's `lock` file.

Also, I started receiving this install warning, which might be related:
```
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: webpack@4.46.0
npm WARN node_modules/webpack
npm WARN   webpack@"^4.44.2" from package-build-stats@7.2.2
npm WARN   node_modules/package-build-stats
npm WARN     package-build-stats@"^7.2.2" from rollpkg@0.5.5
npm WARN     node_modules/rollpkg
npm WARN   8 more (css-loader, esbuild-loader, esbuild-webpack-plugin, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer webpack@"^5" from string-replace-loader@3.0.1
npm WARN node_modules/string-replace-loader
npm WARN   string-replace-loader@"^3.0.1" from package-build-stats@7.2.2
npm WARN   node_modules/package-build-stats
```

**Comment by bpierre** [comment]
csso-webpack-plugin has been updated: https://github.com/zoobestik/csso-webpack-plugin/commit/5980315d6983abbfd858f3e7adda8024f4da07f3

**Comment by rafgraph** [comment]
Hi @pastelsky, would it possible to update `csso-webpack-plugin` to `2.0.0-beta.3` to fix this issue? Thanks.
